name: taqyeemi
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  flutter_riverpod: ^2.1.3
  lottie: ^2.1.0
  http: ^0.13.5
  flutter_zoom_drawer: ^3.0.3
  circle_nav_bar: ^2.0.1+1
  flutter_native_splash: ^2.2.16
  awesome_snackbar_content: ^0.1.0
  cloud_firestore: ^4.3.1
  routemaster: ^1.0.1
  fpdart: ^0.4.1
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
